version: "3.8"
services:
    client:
        image: client-dev-i
        build:
            dockerfile: Dockerfile.dev
        container_name: client-dev-c
        volumes:
            - ./client:/client
            - node_modules:/client/node_modules/
        ports:
            - "5173:80"
        environment:
            - NODE_ENV=DEV
volumes:
    node_modules:
