version: "3.8"
services:
    client:
        image: client-prod-i
        build:
            dockerfile: Dockerfile.prod
        container_name: client-prod-c
        ports:
            - "5173:80"
        environment:
            - NODE_ENV=PROD
