version: "3.8"
services:
    postgres:
        image: postgres:13-alpine
        restart: always
        env_file:
            -   db.env
        ports:
            - "5432:5432"
        volumes:
            -   ./postgresql/data:/var/lib/postgresql/data
    client:
        image: client-dev-i
        build:
            dockerfile: Dockerfile.dev
        container_name: client-dev-c
        volumes:
            - ./client:/client
            - node_modules:/client/node_modules/
        ports:
            - "5173:5173"
        environment:
            - NODE_ENV=DEV

volumes:
    node_modules:
